# Use postgres/example user/password credentials
# https://www.postgresql.org/docs/9.4/pgstatstatements.html

version: '3.1'
services:
  db:
    image: postgres
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8050:8050